/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthcheck minimal
         * @description Retourne "pong" si l'application est vivante.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description L'application répond */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Test d'envoi d'emails
         * @description Envoie 5 emails de test à l'adresse fournie (sujet seul, avec cc, avec bcc, avec corps HTML, avec pièce jointe) pour vérifier la pipeline d'emails.
         */
        get: {
            parameters: {
                query: {
                    /** @description Adresse email destinataire des tests */
                    to: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tous les emails ont été envoyés avec succès */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/traffic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * État du trafic live
         * @description Récupère en parallèle les tuiles MVT de la source trafic couvrant Antananarivo, ne conserve que le layer "speeds", les convertit en GeoJSON et les fusionne en une seule FeatureCollection.
         *     Best-effort : si une ou plusieurs tuiles échouent (timeout, erreur réseau), elles sont ignorées et l'en-tête `X-Predicta-Partial: true` est posé sur la réponse — le corps reste un GeoJSON valide mais géographiquement incomplet. Aucune persistence.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description FeatureCollection GeoJSON des segments trafic. Toujours 200 même en cas de résultat partiel : voir l'en-tête X-Predicta-Partial. */
                200: {
                    headers: {
                        /** @description Présent et égal à "true" uniquement si au moins une tuile a échoué et a été ignorée (résultat incomplet). Absent sinon. */
                        "X-Predicta-Partial"?: "true";
                        [name: string]: unknown;
                    };
                    content: {
                        "application/geo+json": components["schemas"]["TrafficFeatureCollection"];
                    };
                };
                /** @description Clé API absente ou invalide (en-tête X-API-Key). */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quartiers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recherche de quartiers
         * @description Recherche les quartiers de Tana dont le nom contient `q` (insensible à la casse), triés par nom. `q` vide ou absent = tous les quartiers. Renvoie nom + centroïde, pour recentrer la carte sur le quartier.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Sous-chaîne du nom recherchée. Vide = tous. */
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Liste des quartiers correspondants. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QuartierView"][];
                    };
                };
                /** @description Clé API absente ou invalide (en-tête X-API-Key). */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Quartier de Tana (nom + centroïde) pour recentrer la carte. */
        QuartierView: {
            /** @example Analakely */
            name: string;
            /**
             * Format: double
             * @example 47.521
             */
            lon: number;
            /**
             * Format: double
             * @example -18.91
             */
            lat: number;
        };
        /** @description FeatureCollection GeoJSON (RFC 7946) des segments trafic. */
        TrafficFeatureCollection: {
            /** @enum {string} */
            type: "FeatureCollection";
            features: components["schemas"]["TrafficFeature"][];
        };
        /** @description Un segment routier observé, issu du layer "speeds". */
        TrafficFeature: {
            /** @enum {string} */
            type: "Feature";
            properties: components["schemas"]["SpeedProperties"];
            geometry: components["schemas"]["LineGeometry"];
        };
        /** @description Propriétés du segment, décodées des tags MVT du layer "speeds" : nom de la route, vitesse et ratio de congestion. */
        SpeedProperties: {
            /**
             * @description Nom de la route (tag MVT "name"). Absent si la source ne le fournit pas pour ce segment. Sert à la recherche par route côté client.
             * @example Avenue de l'Indépendance
             */
            name?: string;
            /**
             * @description Vitesse observée en km/h.
             * @example 32
             */
            speed?: number;
            /**
             * Format: double
             * @description Ratio vitesse observée / vitesse libre (signal de congestion). Calculé par la source contre sa propre vitesse libre, donc non dérivable de la baseline OSM.
             * @example 0.9
             */
            rate?: number;
        };
        /** @description Géométrie ligne en WGS84. Une position est un couple [lon, lat]. Le layer "speeds" ne produit que des lignes : LineString (un segment) ou MultiLineString (plusieurs). */
        LineGeometry: {
            /** @enum {string} */
            type: "LineString" | "MultiLineString";
            /** @description LineString -> tableau de positions [[lon,lat], ...]. MultiLineString -> tableau de lignes [[[lon,lat], ...], ...]. */
            coordinates: number[][] | number[][][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
